create table if not exists "CROSSROADPRICE"(
"ROADIDONE" INTEGER NOT NULL,
"ROADIDTWO" INTEGER NOT NULL,
"DAYHOUR" INTEGER NOT NULL,
"ROADPRICE"."TIME" DOUBLE,
constraint dos_pk primary key("ROADIDONE", "ROADIDTWO", "DAYHOUR"));